In [209]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import os

In [210]:
output_data_file = "../Resources/political_affiliation.csv"
df = pd.read_csv(output_data_file)
df.head()

,Location,Governor Political Affiliation,State Senate Majority Political Affiliation,State House Majority Political Affiliation,State Attorney General Political Affiliation,State Insurance Commissioner Political Affiliation,Footnotes,Lat,Long
0,Alabama,Republican,Republican,Republican,Republican,Appointed,NaN,32.318231,-86.902298
1,Alaska,Republican,Republican,Republican,Appointed,Appointed,NaN,63.588753,-154.493062
2,Arizona,Republican,Republican,Republican,Republican,Appointed,NaN,34.048928,-111.093731
3,Arkansas,Republican,Republican,Republican,Republican,Appointed,NaN,35.201050,-91.831833
4,California,Democrat,Democrat,Democrat,Appointed,Democrat,NaN,36.778261,-119.417932

In [211]:
df.rename(columns={'Location':'State', 'Governor Political Affiliation':'Gov_Political_Affiliation' }, inplace=True)
df.head()

,State,Gov_Political_Affiliation,State Senate Majority Political Affiliation,State House Majority Political Affiliation,State Attorney General Political Affiliation,State Insurance Commissioner Political Affiliation,Footnotes,Lat,Long
0,Alabama,Republican,Republican,Republican,Republican,Appointed,NaN,32.318231,-86.902298
1,Alaska,Republican,Republican,Republican,Appointed,Appointed,NaN,63.588753,-154.493062
2,Arizona,Republican,Republican,Republican,Republican,Appointed,NaN,34.048928,-111.093731
3,Arkansas,Republican,Republican,Republican,Republican,Appointed,NaN,35.201050,-91.831833
4,California,Democrat,Democrat,Democrat,Appointed,Democrat,NaN,36.778261,-119.417932

In [212]:
df.drop(['Footnotes','State Senate Majority Political Affiliation',	'State House Majority Political Affiliation','State Attorney General Political Affiliation', 'State Insurance Commissioner Political Affiliation'], axis = 1, inplace = True)

In [213]:
df.head()

        State Gov_Political_Affiliation        Lat        Long
0     Alabama                Republican  32.318231  -86.902298
1      Alaska                Republican  63.588753 -154.493062
2     Arizona                Republican  34.048928 -111.093731
3    Arkansas                Republican  35.201050  -91.831833
4  California                  Democrat  36.778261 -119.417932

In [214]:
data_df = pd.DataFrame(df, columns=['State', 'Gov_Political_Affiliation', 'Lat', 'Long'])
# result = data_df.to_json(orient="split")
  



# print(json.dumps(data_df.to_dict()))

# data_df = json.dumps(data_df.to_dict())
# json.dumps(parsed, indent=4)

data = data_df.to_json(r'/Users/xilo/Desktop/Bootcamp/Project/Project-3-Gun-Incidents/Resources/election.json', orient='split')

In [215]:
data_df.to_csv('clean_political_affiliation.csv')