In [117]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# # Import API key
# from api_keys import g_key

# # Configure gmaps with API key
# gmaps.configure(api_key = g_key)

In [118]:
output_data_file = "../Resources/2020-SENATE-precinct-general.csv"
df = pd.read_csv(output_data_file)
df.head()

  party_simplified  votes  year stage    state state_po
0              NaN      0  2020   GEN  ALABAMA       AL
1              NaN      1  2020   GEN  ALABAMA       AL
2              NaN      0  2020   GEN  ALABAMA       AL
3         DEMOCRAT    153  2020   GEN  ALABAMA       AL
4       REPUBLICAN    218  2020   GEN  ALABAMA       AL

In [119]:
df.rename(columns={'party_simplified':'political_party'}, inplace=True)

In [122]:
data_df = df.dropna(how='any')

In [123]:
data_df.count()

political_party    685204
votes              685204
year               685204
stage              685204
state              685204
state_po           685204
dtype: int64

In [124]:
data_df["political_party"].value_counts()

DEMOCRAT       204827
OTHER          196195
REPUBLICAN     180325
LIBERTARIAN     95828
NONPARTISAN      8029
Name: political_party, dtype: int64

In [126]:
data_df = data_df.replace(
    {"LIBERTARIAN": "OTHER ", "NONPARTISAN": "OTHER"}
)

data_df

       political_party  votes  year stage    state state_po
3             DEMOCRAT    153  2020   GEN  ALABAMA       AL
4           REPUBLICAN    218  2020   GEN  ALABAMA       AL
8             DEMOCRAT    371  2020   GEN  ALABAMA       AL
9           REPUBLICAN   1668  2020   GEN  ALABAMA       AL
13            DEMOCRAT   1073  2020   GEN  ALABAMA       AL
...                ...    ...   ...   ...      ...      ...
759369      REPUBLICAN    417  2020   GEN  WYOMING       WY
759373        DEMOCRAT    217  2020   GEN  WYOMING       WY
759374      REPUBLICAN    730  2020   GEN  WYOMING       WY
759378        DEMOCRAT      2  2020   GEN  WYOMING       WY
759379      REPUBLICAN     90  2020   GEN  WYOMING       WY

[685204 rows x 6 columns]

In [128]:
votes_total_group = data_df.groupby(["political_party", "state"])
votes_total_group.head()

       political_party  votes  year stage    state state_po
3             DEMOCRAT    153  2020   GEN  ALABAMA       AL
4           REPUBLICAN    218  2020   GEN  ALABAMA       AL
8             DEMOCRAT    371  2020   GEN  ALABAMA       AL
9           REPUBLICAN   1668  2020   GEN  ALABAMA       AL
13            DEMOCRAT   1073  2020   GEN  ALABAMA       AL
...                ...    ...   ...   ...      ...      ...
757056      REPUBLICAN     49  2020   GEN  WYOMING       WY
757057      REPUBLICAN     90  2020   GEN  WYOMING       WY
757058      REPUBLICAN    175  2020   GEN  WYOMING       WY
757059      REPUBLICAN    297  2020   GEN  WYOMING       WY
757060      REPUBLICAN    298  2020   GEN  WYOMING       WY

[510 rows x 6 columns]